require:
  - "rubocop-performance"
  - "rubocop-rspec"
  - "rubocop-rails"
  - "rubocop-rspec_rails"
  - "rubocop-factory_bot"

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5
  TargetRailsVersion: 7.2

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - "app/concepts/**/*"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Exclude:
    - "spec/models/**/*"
