default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  <<: *default
  database: tenant_custom_fields_development

test:
  <<: *default
  database: tenant_custom_fields_test

production:
  <<: *default
  database: tenant_custom_fields_production
  username: tenant_custom_fields
  password: <%= ENV["TENANT_CUSTOM_FIELDS_DATABASE_PASSWORD"] %>
